<?php
declare(strict_types=1);
require_once __DIR__ . '/accounts_common.php';
$user=qbook_require_user();qbook_require_role($user,['ADMIN']);production_require_method('POST');$input=production_input();
accounts_endpoint(function() use($user,$input): array {
    $rowId=(int)($input['statement_row_id']??0);$sourceType=strtoupper(trim((string)($input['source_type']??'')));$sourceId=(int)($input['source_record_id']??0);if($rowId<=0||$sourceId<=0||!in_array($sourceType,['PETTY_CASH_FUNDING','GENERAL_EXPENSE'],true))accounts_fail('INVALID_BANK_MATCH');$db=production_db();
    return accounts_transaction($db,function() use($db,$user,$rowId,$sourceType,$sourceId): array {
        $s=$db->prepare("SELECT * FROM qbook_bank_statement_rows WHERE id=? FOR UPDATE");$s->execute([$rowId]);$row=$s->fetch();if(!$row)accounts_fail('BANK_ROW_NOT_FOUND',404);if(in_array($row['status'],['MATCHED','RECONCILED'],true))accounts_fail('BANK_ROW_ALREADY_MATCHED',409);
        if($sourceType==='PETTY_CASH_FUNDING'){$f=$db->prepare("SELECT bank_account_id,funding_date AS source_date,amount,bank_reference,NULL AS source_narration FROM qbook_petty_cash_fundings WHERE id=? AND journal_id IS NOT NULL");$notFound='FUNDING_NOT_FOUND';}else{$f=$db->prepare("SELECT bank_account_id,expense_date AS source_date,amount,bank_reference,description AS source_narration FROM qbook_general_expenses WHERE id=? AND status='APPROVED' AND journal_id IS NOT NULL");$notFound='EXPENSE_NOT_FOUND';}$f->execute([$sourceId]);$source=$f->fetch();if(!$source)accounts_fail($notFound,404);
        $rowMinor=accounts_money_minor($row['amount'],false);$sourceMinor=accounts_money_minor($source['amount'],false);$days=abs((new DateTimeImmutable($row['transaction_date']))->diff(new DateTimeImmutable($source['source_date']))->days);
        if((int)$source['bank_account_id']!==(int)$row['bank_account_id']||$rowMinor!==-$sourceMinor||$days>3)accounts_fail('BANK_MATCH_MISMATCH',409);
        $rowReference=bank_normalize_text($row['bank_reference']??'',150);$sourceReference=bank_normalize_text($source['bank_reference']??'',150);if($rowReference!==''&&($sourceReference===''||$rowReference!==$sourceReference))accounts_fail('BANK_REFERENCE_MISMATCH',409);$narrationSignal=bank_normalize_text($row['narration']??'',500)!==''&&bank_normalize_text($row['narration']??'',500)===bank_normalize_text($source['source_narration']??'',500);
        $db->prepare("INSERT INTO qbook_bank_matches(statement_row_id,source_type,source_record_id,matched_by) VALUES(?,?,?,?)")->execute([$rowId,$sourceType,$sourceId,(int)$user['id']]);$match=(int)$db->lastInsertId();$db->prepare("UPDATE qbook_bank_statement_rows SET status='RECONCILED',potential_source_type=?,potential_source_id=? WHERE id=?")->execute([$sourceType,$sourceId,$rowId]);accounts_audit($db,$user,'BANK_ROW_RECONCILED','BANK_MATCH',$match,['statement_row_id'=>$rowId,'source_type'=>$sourceType,'source_record_id'=>$sourceId,'reference_signal'=>$rowReference!==''?'EXACT':'ABSENT','narration_signal'=>$narrationSignal?'EXACT':'AVAILABLE_FOR_REVIEW']);return ['match'=>['id'=>$match,'status'=>'RECONCILED']];
    });
});
