<?php
declare(strict_types=1);require_once __DIR__.'/estimate_common.php';$user=billing_require_admin();production_require_method('POST');$in=production_input();
accounts_endpoint(function()use($user,$in):array{$db=production_db();return accounts_transaction($db,function()use($db,$user,$in):array{
 $id=(int)($in['id']??0);$client=billing_client($db,$in['client_id']??0);$date=accounts_date($in['estimate_date']??'');$valid=accounts_date($in['valid_until']??'');if($valid<$date)accounts_fail('INVALID_ESTIMATE_VALIDITY');
 $mode=strtoupper((string)($in['vat_mode']??'NONE'));if(!in_array($mode,['NONE','VAT_EXCLUSIVE','VAT_INCLUSIVE'],true))accounts_fail('INVALID_VAT_MODE');$tax=$mode==='NONE'?null:billing_tax_code($db,$in['vat_tax_code_id']??0,'VAT',$date);
 $lines=estimate_lines($db,$in,(int)$client['id'],$mode,$tax);$tot=billing_totals($lines);
 if($id>0){$old=estimate_locked($db,$id);if($old['status']!=='DRAFT')accounts_fail('SENT_ESTIMATE_IMMUTABLE',409);$db->prepare('DELETE FROM qbook_estimate_lines WHERE estimate_id=?')->execute([$id]);$ref=(int)$old['reference_no'];}
 else{$ref=billing_allocate_reference($db,'qbook_estimate_references');$revision=accounts_nullable_id($in['revision_of_estimate_id']??null);if($revision!==null){$q=$db->prepare("SELECT id FROM qbook_estimates WHERE id=? AND status<>'DRAFT'");$q->execute([$revision]);if(!$q->fetch())accounts_fail('INVALID_ESTIMATE_REVISION',409);}$db->prepare('INSERT INTO qbook_estimates(reference_no,revision_of_estimate_id,client_id,client_name_snapshot,created_by)VALUES(?,?,?,?,?)')->execute([$ref,$revision,$client['id'],$client['name'],$user['id']]);$id=(int)$db->lastInsertId();}
 $db->prepare('UPDATE qbook_estimates SET client_id=?,client_name_snapshot=?,estimate_date=?,valid_until=?,vat_mode=?,vat_tax_code_id=?,vat_rate_snapshot=?,net_amount=?,vat_amount=?,total_amount=?,notes=?,terms_snapshot=? WHERE id=?')->execute([$client['id'],$client['name'],$date,$valid,$mode,$tax['id']??null,$tax['rate_percent']??null,accounts_minor_decimal($tot['net']),accounts_minor_decimal($tot['vat']),accounts_minor_decimal($tot['gross']),production_clean_text($in['notes']??'',2000,'INVALID_NOTES',false)?:null,production_clean_text($in['terms']??'Advance Payment',500,'INVALID_TERMS'),$id]);
 $li=$db->prepare('INSERT INTO qbook_estimate_lines(estimate_id,line_no,description,quantity,unit_name,unit_price,entered_amount,taxable,net_amount,vat_amount,gross_amount,revenue_account_id,project_id,project_snapshot,mixer_id,mixer_snapshot)VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)');foreach($lines as$l)$li->execute([$id,$l['line_no'],$l['description'],$l['quantity'],$l['unit_name'],$l['unit_price_minor']===null?null:accounts_minor_decimal($l['unit_price_minor']),accounts_minor_decimal($l['entered_minor']),$l['taxable'],accounts_minor_decimal($l['net_minor']),accounts_minor_decimal($l['vat_minor']),accounts_minor_decimal($l['gross_minor']),$l['revenue_account_id'],$l['project_id'],$l['project_snapshot'],$l['mixer_id'],$l['mixer_snapshot']]);
 accounts_audit($db,$user,'ESTIMATE_DRAFT_SAVED','ESTIMATE',$id,['reference'=>billing_ref('ESTIMATE',$ref)]);return['estimate'=>['id'=>$id,'reference'=>billing_ref('ESTIMATE',$ref),'status'=>'DRAFT','total'=>accounts_minor_decimal($tot['gross'])]];
});});
