<?php
declare(strict_types=1);
require_once __DIR__ . '/accounts_common.php';
$user=qbook_require_user();qbook_require_role($user,['ADMIN']);production_require_method('GET');
accounts_endpoint(function(): array {$db=production_db();
  $petty=$db->query("SELECT e.id AS source_record_id,r.reference_no,e.expense_date,e.amount,COALESCE(e.supplier_paid_to,'') AS supplier_paid_to,COALESCE(e.description,'') AS description,'PETTY_CASH' AS source_type,u.full_name AS source_name,e.status AS lifecycle_status,e.journal_id,j.reference_no AS original_journal_reference,e.reversal_journal_id,rj.reference_no AS reversal_journal_reference,e.void_reason,e.voided_at,vu.full_name AS voided_by_name,(SELECT COUNT(*) FROM qbook_financial_evidence v WHERE v.source_type='PETTY_CASH_EXPENSE' AND v.source_record_id=e.id) AS evidence_count FROM qbook_petty_cash_expenses e JOIN qbook_users u ON u.id=e.custodian_user_id LEFT JOIN qbook_petty_cash_expense_references r ON r.expense_id=e.id LEFT JOIN qbook_financial_journals j ON j.id=e.journal_id LEFT JOIN qbook_financial_journals rj ON rj.id=e.reversal_journal_id LEFT JOIN qbook_users vu ON vu.id=e.voided_by")->fetchAll();
  $general=$db->query("SELECT e.id AS source_record_id,r.reference_no,e.expense_date,e.amount,COALESCE(e.supplier_name_snapshot,'') AS supplier_paid_to,COALESCE(e.description,'') AS description,'BANK' AS source_type,b.name AS source_name,e.status AS lifecycle_status,e.journal_id,j.reference_no AS original_journal_reference,e.reversal_journal_id,rj.reference_no AS reversal_journal_reference,e.void_reason,e.voided_at,vu.full_name AS voided_by_name,(SELECT COUNT(*) FROM qbook_financial_evidence v WHERE v.source_type='GENERAL_EXPENSE' AND v.source_record_id=e.id) AS evidence_count FROM qbook_general_expenses e LEFT JOIN qbook_general_expense_references r ON r.expense_id=e.id LEFT JOIN qbook_bank_accounts b ON b.id=e.bank_account_id LEFT JOIN qbook_financial_journals j ON j.id=e.journal_id LEFT JOIN qbook_financial_journals rj ON rj.id=e.reversal_journal_id LEFT JOIN qbook_users vu ON vu.id=e.voided_by")->fetchAll();
  $pettyLines=$db->prepare("SELECT l.id,l.line_no,l.item_description,l.expense_account_id,l.amount,l.cost_centre_id,l.client_id,l.project_id,l.mixer_id,a.code AS account_code,a.name AS category,cc.code AS cost_centre_code,cc.name AS cost_centre_name,c.name AS client_name,p.name AS project_name,m.code AS mixer_code FROM qbook_petty_cash_expense_lines l JOIN qbook_accounts_chart a ON a.id=l.expense_account_id LEFT JOIN qbook_cost_centres cc ON cc.id=l.cost_centre_id LEFT JOIN qbook_clients c ON c.id=l.client_id LEFT JOIN qbook_projects p ON p.id=l.project_id LEFT JOIN qbook_mixers m ON m.id=l.mixer_id WHERE l.expense_id=? ORDER BY l.line_no");$generalLines=$db->prepare("SELECT l.id,l.line_no,l.item_description,l.expense_account_id,l.amount,l.cost_centre_id,l.client_id,l.project_id,l.mixer_id,a.code AS account_code,a.name AS category,cc.code AS cost_centre_code,cc.name AS cost_centre_name,c.name AS client_name,p.name AS project_name,m.code AS mixer_code FROM qbook_general_expense_lines l JOIN qbook_accounts_chart a ON a.id=l.expense_account_id LEFT JOIN qbook_cost_centres cc ON cc.id=l.cost_centre_id LEFT JOIN qbook_clients c ON c.id=l.client_id LEFT JOIN qbook_projects p ON p.id=l.project_id LEFT JOIN qbook_mixers m ON m.id=l.mixer_id WHERE l.expense_id=? ORDER BY l.line_no");
  $rows=[];foreach($petty as $row){$row['reference_no']=accounts_petty_cash_reference($row['reference_no'])??'Reference pending';$pettyLines->execute([(int)$row['source_record_id']]);$row['lines']=$pettyLines->fetchAll();$rows[]=$row;}foreach($general as $row){$row['reference_no']=accounts_general_expense_reference($row['reference_no']);$generalLines->execute([(int)$row['source_record_id']]);$row['lines']=$generalLines->fetchAll();$rows[]=$row;}
  foreach($rows as &$row){$row['category']=count($row['lines'])===1?$row['lines'][0]['category']:count($row['lines']).' expense lines';$row['client_name']=null;$row['project_name']=null;$row['mixer_code']=null;$status=$row['lifecycle_status'];$row['posting_status']=$status==='VOIDED'?'VOIDED / REVERSED':($status==='APPROVED'?'APPROVED / POSTED':$status.' / NOT POSTED');}unset($row);usort($rows,fn(array $a,array $b): int=>strcmp(($b['expense_date']??'').'|'.str_pad((string)$b['source_record_id'],20,'0',STR_PAD_LEFT),($a['expense_date']??'').'|'.str_pad((string)$a['source_record_id'],20,'0',STR_PAD_LEFT)));return ['expenses'=>$rows];
});
