<?php
declare(strict_types=1);
require_once __DIR__ . '/accounts_common.php';
$user=qbook_require_user();qbook_require_role($user,['ADMIN']);production_require_method('POST');$input=production_input();
accounts_endpoint(function() use($user,$input): array {
    $type=strtoupper(trim((string)($input['source_type']??'')));$id=(int)($input['source_record_id']??0);
    if(!in_array($type,['PETTY_CASH_EXPENSE','GENERAL_EXPENSE'],true)||$id<=0) accounts_fail('EXPENSE_SOURCE_NOT_SUPPORTED');
    $reason=production_clean_text($input['reason']??'',500,'VOID_REASON_REQUIRED');$date=accounts_date($input['void_date']??gmdate('Y-m-d'));$basis=strtoupper(trim((string)($input['void_basis']??'')));$db=production_db();
    return accounts_transaction($db,function() use($db,$user,$id,$type,$reason,$date,$basis): array {
        $general=$type==='GENERAL_EXPENSE';$expenseTable=$general?'qbook_general_expenses':'qbook_petty_cash_expenses';$referenceTable=$general?'qbook_general_expense_references':'qbook_petty_cash_expense_references';$lineHistory=$general?'qbook_general_expense_line_reclassifications':'qbook_petty_cash_line_reclassifications';
        $s=$db->prepare("SELECT e.*,r.reference_no,j.reference_no AS original_journal_reference FROM {$expenseTable} e LEFT JOIN {$referenceTable} r ON r.expense_id=e.id LEFT JOIN qbook_financial_journals j ON j.id=e.journal_id WHERE e.id=? FOR UPDATE");$s->execute([$id]);$expense=$s->fetch();if(!$expense)accounts_fail('EXPENSE_NOT_FOUND',404);if($expense['status']==='VOIDED'||$expense['reversal_journal_id']!==null)accounts_fail('EXPENSE_ALREADY_VOIDED',409);if($expense['status']!=='APPROVED'||$expense['journal_id']===null)accounts_fail('EXPENSE_NOT_VOIDABLE',409);
        $match=$db->prepare("SELECT bm.id,bm.statement_row_id,s.amount FROM qbook_bank_matches bm JOIN qbook_bank_statement_rows s ON s.id=bm.statement_row_id WHERE bm.source_type=? AND bm.source_record_id=?");$match->execute([$type,$id]);$matches=$match->fetchAll();
        if($general){if(!in_array($basis,['DUPLICATE_ACCOUNTING','ECONOMICALLY_NEVER_EXISTED','ACTUAL_LINKED_REFUND'],true))accounts_fail('BANK_VOID_BASIS_REQUIRED');if($matches!==[]&&$basis==='ECONOMICALLY_NEVER_EXISTED')accounts_fail('MATCHED_BANK_DEBIT_CANNOT_BE_VOIDED',409);if($basis==='ACTUAL_LINKED_REFUND'){$refund=$db->prepare("SELECT COALESCE(SUM(r.amount),0) FROM qbook_general_expense_refunds r JOIN qbook_bank_statement_rows s ON s.id=r.statement_row_id AND s.amount>0 WHERE r.expense_id=?");$refund->execute([$id]);$refundMinor=accounts_money_minor((string)$refund->fetchColumn(),false);if($refundMinor<accounts_money_minor($expense['amount'],false))accounts_fail('FULL_ACTUAL_REFUND_REQUIRED',409);}}
        $lineReversals=[];$line=$db->prepare("SELECT id,journal_id FROM {$lineHistory} WHERE expense_id=? AND journal_id IS NOT NULL AND reversal_journal_id IS NULL ORDER BY id DESC FOR UPDATE");$line->execute([$id]);foreach($line->fetchAll() as $change){$r=accounts_reverse_journal($db,$user,(int)$change['journal_id'],$reason,$date);$db->prepare("UPDATE {$lineHistory} SET reversal_journal_id=? WHERE id=?")->execute([$r['id'],(int)$change['id']]);$lineReversals[]=$r;}
        if(!$general){$legacy=$db->prepare("SELECT id,journal_id FROM qbook_petty_cash_expense_reclassifications WHERE expense_id=? AND journal_id IS NOT NULL AND reversal_journal_id IS NULL ORDER BY id DESC FOR UPDATE");$legacy->execute([$id]);foreach($legacy->fetchAll() as $change){$r=accounts_reverse_journal($db,$user,(int)$change['journal_id'],$reason,$date);$db->prepare("UPDATE qbook_petty_cash_expense_reclassifications SET reversal_journal_id=? WHERE id=?")->execute([$r['id'],(int)$change['id']]);$lineReversals[]=$r;}}
        $reversal=accounts_reverse_journal($db,$user,(int)$expense['journal_id'],$reason,$date);$db->prepare("UPDATE {$expenseTable} SET status='VOIDED',reversal_journal_id=?,voided_by=?,voided_at=UTC_TIMESTAMP(),void_reason=? WHERE id=? AND status='APPROVED' AND reversal_journal_id IS NULL")->execute([$reversal['id'],(int)$user['id'],$reason,$id]);$reference=$general?accounts_general_expense_reference($expense['reference_no']):accounts_petty_cash_reference($expense['reference_no']);accounts_audit($db,$user,'EXPENSE_VOIDED',$type,$id,['reference_no'=>$reference,'void_basis'=>$general?$basis:'GENUINE_VOID','original_journal_id'=>(int)$expense['journal_id'],'reversal_journal_id'=>$reversal['id'],'reclassification_reversals'=>$lineReversals,'reason'=>$reason,'bank_matches_preserved'=>count($matches)]);return ['expense'=>['id'=>$id,'source_type'=>$type,'reference_no'=>$reference,'status'=>'VOIDED'],'reversal'=>$reversal,'bank_matches_preserved'=>count($matches)];
    });
});
