<?php
declare(strict_types=1);
require_once __DIR__ . '/accounts_common.php';
$user=qbook_require_user();qbook_require_role($user,['ADMIN']);production_require_method('POST');$input=production_input();
accounts_endpoint(function() use($user,$input): array {$type=strtoupper(trim((string)($input['source_type']??'')));$expenseId=(int)($input['source_record_id']??0);$lineId=(int)($input['line_id']??0);if(!in_array($type,['PETTY_CASH_EXPENSE','GENERAL_EXPENSE'],true)||$expenseId<=0||$lineId<=0)accounts_fail('EXPENSE_LINE_SOURCE_NOT_SUPPORTED');$reason=production_clean_text($input['reason']??'',500,'RECLASSIFICATION_REASON_REQUIRED');$db=production_db();return accounts_transaction($db,function() use($db,$user,$input,$type,$expenseId,$lineId,$reason): array {
  $general=$type==='GENERAL_EXPENSE';$expenseTable=$general?'qbook_general_expenses':'qbook_petty_cash_expenses';$lineTable=$general?'qbook_general_expense_lines':'qbook_petty_cash_expense_lines';$historyTable=$general?'qbook_general_expense_line_reclassifications':'qbook_petty_cash_line_reclassifications';$module=$general?'GENERAL_EXPENSE_LINE_RECLASS':'PETTY_CASH_LINE_RECLASS';
  $s=$db->prepare("SELECT * FROM {$expenseTable} WHERE id=? FOR UPDATE");$s->execute([$expenseId]);$expense=$s->fetch();if(!$expense)accounts_fail('EXPENSE_NOT_FOUND',404);if($expense['status']!=='APPROVED'||$expense['journal_id']===null)accounts_fail('EXPENSE_NOT_RECLASSIFIABLE',409);
  $l=$db->prepare("SELECT * FROM {$lineTable} WHERE id=? AND expense_id=? FOR UPDATE");$l->execute([$lineId,$expenseId]);$base=$l->fetch();if(!$base)accounts_fail('EXPENSE_LINE_NOT_FOUND',404);$latest=$db->prepare("SELECT * FROM {$historyTable} WHERE line_id=? ORDER BY version_no DESC LIMIT 1 FOR UPDATE");$latest->execute([$lineId]);$prior=$latest->fetch();$before=$prior?json_decode($prior['after_snapshot'],true,512,JSON_THROW_ON_ERROR):['expense_account_id'=>(int)$base['expense_account_id'],'description'=>$base['item_description'],'cost_centre_id'=>$base['cost_centre_id'],'client_id'=>$base['client_id'],'project_id'=>$base['project_id'],'mixer_id'=>$base['mixer_id'],'amount'=>$base['amount']];
  $before['cost_centre_id']=$before['cost_centre_id']??null;$after=['expense_account_id'=>(int)($input['expense_account_id']??0),'description'=>production_clean_text($input['description']??$before['description'],500,'LINE_DESCRIPTION_REQUIRED'),'cost_centre_id'=>accounts_nullable_id($input['cost_centre_id']??null),'client_id'=>accounts_nullable_id($input['client_id']??null),'project_id'=>accounts_nullable_id($input['project_id']??null),'mixer_id'=>accounts_nullable_id($input['mixer_id']??null),'amount'=>$before['amount']];$checked=accounts_expense_lines($db,[$after])[0];$after['expense_account_id']=$checked['expense_account_id'];$after['cost_centre_id']=$checked['cost_centre_id'];$version=(int)($prior['version_no']??0)+1;
  if($before['expense_account_id']===$after['expense_account_id']&&$before['description']===$after['description']&&$before['cost_centre_id']===$after['cost_centre_id']&&$before['client_id']===$after['client_id']&&$before['project_id']===$after['project_id']&&$before['mixer_id']===$after['mixer_id'])accounts_fail('NO_RECLASSIFICATION_CHANGE');
  $db->prepare("INSERT INTO {$historyTable}(expense_id,line_id,version_no,before_snapshot,after_snapshot,reason,reclassified_by) VALUES(?,?,?,?,?,?,?)")->execute([$expenseId,$lineId,$version,json_encode($before,JSON_THROW_ON_ERROR),json_encode($after,JSON_THROW_ON_ERROR),$reason,(int)$user['id']]);$changeId=(int)$db->lastInsertId();$minor=accounts_money_minor($before['amount'],false);
  $journal=accounts_post_journal($db,$user,['transaction_date'=>gmdate('Y-m-d'),'description'=>'Line reclassification: '.$reason,'source_module'=>$module,'source_record_id'=>$changeId,'entry_kind'=>'REPLACEMENT','approved_by'=>(int)$user['id']],[['account_id'=>$after['expense_account_id'],'debit_minor'=>$minor,'credit_minor'=>0,'cost_centre_id'=>$after['cost_centre_id'],'client_id'=>$after['client_id'],'project_id'=>$after['project_id'],'mixer_id'=>$after['mixer_id'],'description'=>$after['description']],['account_id'=>(int)$before['expense_account_id'],'debit_minor'=>0,'credit_minor'=>$minor,'cost_centre_id'=>$before['cost_centre_id'],'client_id'=>$before['client_id'],'project_id'=>$before['project_id'],'mixer_id'=>$before['mixer_id'],'description'=>'Reclassify from: '.$before['description']]]);$db->prepare("UPDATE {$historyTable} SET journal_id=? WHERE id=?")->execute([$journal['id'],$changeId]);$db->prepare("UPDATE {$lineTable} SET expense_account_id=?,item_description=?,cost_centre_id=?,client_id=?,project_id=?,mixer_id=? WHERE id=? AND expense_id=?")->execute([$after['expense_account_id'],$after['description'],$after['cost_centre_id'],$after['client_id'],$after['project_id'],$after['mixer_id'],$lineId,$expenseId]);accounts_audit($db,$user,'EXPENSE_LINE_RECLASSIFIED',$type,$expenseId,['line_id'=>$lineId,'version'=>$version,'before'=>$before,'after'=>$after,'journal_id'=>$journal['id'],'asset_impact'=>'0.00','reason'=>$reason]);return ['reclassification'=>['id'=>$changeId,'line_id'=>$lineId,'version'=>$version,'journal'=>$journal],'asset_impact'=>'0.00'];
});});
