<?php
declare(strict_types=1);
require_once __DIR__ . '/accounts_common.php';
$user=qbook_require_user();production_require_method('GET');$id=(int)($_GET['evidence_id']??0);if($id<=0)qbook_json(['ok'=>false,'error'=>'EVIDENCE_REQUIRED'],422);
$db=production_db();$s=$db->prepare("SELECT v.*,CASE WHEN v.source_type='PETTY_CASH_EXPENSE' THEN CONCAT('CEH-PC-',LPAD(pr.reference_no,6,'0')) WHEN v.source_type='GENERAL_EXPENSE' THEN CONCAT('CEH-EX-',LPAD(er.reference_no,6,'0')) ELSE NULL END AS business_reference FROM qbook_financial_evidence v LEFT JOIN qbook_petty_cash_expense_references pr ON v.source_type='PETTY_CASH_EXPENSE' AND pr.expense_id=v.source_record_id LEFT JOIN qbook_general_expense_references er ON v.source_type='GENERAL_EXPENSE' AND er.expense_id=v.source_record_id WHERE v.id=?");$s->execute([$id]);$e=$s->fetch();if(!$e)qbook_json(['ok'=>false,'error'=>'EVIDENCE_NOT_FOUND'],404);
$allowed=strtoupper((string)$user['role'])==='ADMIN';if(!$allowed&&$e['source_type']==='PETTY_CASH_EXPENSE'){$x=$db->prepare("SELECT custodian_user_id FROM qbook_petty_cash_expenses WHERE id=?");$x->execute([(int)$e['source_record_id']]);$allowed=(int)$x->fetchColumn()===(int)$user['id'];}
if(!$allowed)qbook_json(['ok'=>false,'error'=>'FORBIDDEN'],403);if($e['storage_driver']!=='MYSQL_BLOB'||$e['evidence_data']===null)qbook_json(['ok'=>false,'error'=>'EVIDENCE_UNAVAILABLE'],409);
$bytes=(string)$e['evidence_data'];if(!hash_equals((string)$e['sha256'],hash('sha256',$bytes)))qbook_json(['ok'=>false,'error'=>'EVIDENCE_INTEGRITY_FAILED'],500);
$downloadName=$e['business_reference']?:'evidence-'.$id;production_discard_output();header('Content-Type: '.$e['mime_type']);header('Content-Length: '.strlen($bytes));header('Content-Disposition: attachment; filename="'.$downloadName.'"');header('Cache-Control: private, no-store');header('X-Content-Type-Options: nosniff');echo $bytes;exit;
