<?php
declare(strict_types=1);
require_once __DIR__ . '/accounts_common.php';
$user=qbook_require_user();qbook_require_role($user,['ADMIN']);production_require_method('POST');$input=production_input();
accounts_endpoint(function() use($user,$input): array {$db=production_db();return accounts_transaction($db,function() use($db,$user,$input): array {
  $bank=accounts_nullable_id($input['bank_account_id']??null);$statement=accounts_nullable_id($input['statement_row_id']??null);$dateRaw=trim((string)($input['expense_date']??''));$date=$dateRaw===''?null:accounts_date($dateRaw);$amountRaw=trim((string)($input['amount']??''));$minor=$amountRaw===''?null:accounts_money_minor($amountRaw);
  if($statement!==null){$s=$db->prepare("SELECT * FROM qbook_bank_statement_rows WHERE id=? FOR UPDATE");$s->execute([$statement]);$row=$s->fetch();if(!$row)accounts_fail('BANK_ROW_NOT_FOUND',404);if(in_array($row['status'],['MATCHED','RECONCILED'],true))accounts_fail('BANK_ROW_ALREADY_MATCHED',409);$rowMinor=accounts_money_minor($row['amount'],false);if($rowMinor>=0)accounts_fail('EXPENSE_REQUIRES_BANK_DEBIT');$bank=(int)$row['bank_account_id'];$date=$row['transaction_date'];$minor=abs($rowMinor);$input['bank_reference']=$row['bank_reference'];if(trim((string)($input['description']??''))==='')$input['description']=$row['narration'];}
  if($bank!==null){$b=$db->prepare("SELECT id FROM qbook_bank_accounts WHERE id=? AND is_active=1");$b->execute([$bank]);if(!$b->fetch())accounts_fail('ACTIVE_BANK_ACCOUNT_REQUIRED');}
  $supplierId=accounts_nullable_id($input['supplier_id']??null);$supplier=$supplierId===null?null:accounts_supplier($db,$supplierId);$oneOff=production_clean_text($input['one_off_payee']??'',200,'INVALID_ONE_OFF_PAYEE',false);if($supplier!==null&&$oneOff!=='')accounts_fail('CHOOSE_SUPPLIER_OR_ONE_OFF_PAYEE');$supplierSnapshot=$supplier['canonical_name']??($oneOff?:null);$lines=accounts_expense_lines($db,$input['lines']??[],false);if($minor!==null&&$lines!==[])accounts_require_line_total($lines,$minor);
  $db->prepare("INSERT INTO qbook_general_expenses(bank_account_id,expense_date,amount,supplier_id,supplier_name_snapshot,description,bank_reference,no_receipt_reason,created_by,created_from_statement_row_id) VALUES(?,?,?,?,?,?,?,?,?,?)")->execute([$bank,$date,$minor===null?null:accounts_minor_decimal($minor),$supplierId,$supplierSnapshot,production_clean_text($input['description']??'',500,'INVALID_DESCRIPTION',false)?:null,production_clean_text($input['bank_reference']??'',150,'INVALID_BANK_REFERENCE',false)?:null,production_clean_text($input['no_receipt_reason']??'',500,'INVALID_NO_RECEIPT_REASON',false)?:null,(int)$user['id'],$statement]);
  $id=(int)$db->lastInsertId();accounts_replace_expense_lines($db,'qbook_general_expense_lines',$id,$lines);$db->prepare("INSERT INTO qbook_general_expense_references(expense_id) VALUES(?)")->execute([$id]);$reference=accounts_general_expense_reference((int)$db->lastInsertId());accounts_audit($db,$user,'GENERAL_EXPENSE_DRAFTED','GENERAL_EXPENSE',$id,['reference_no'=>$reference,'line_count'=>count($lines),'statement_row_id'=>$statement]);return ['expense'=>['id'=>$id,'reference_no'=>$reference,'status'=>'DRAFT']];
});});
