<?php
declare(strict_types=1);require_once __DIR__.'/billing_common.php';$user=billing_require_admin();production_require_method('POST');$in=production_input();accounts_endpoint(function()use($user,$in):array{$db=production_db();return accounts_transaction($db,function()use($db,$user,$in):array{
 $id=(int)($in['id']??0);$client=billing_client($db,$in['client_id']??0);$date=isset($in['invoice_date'])&&$in['invoice_date']!==''?accounts_date($in['invoice_date']):null;$mode=strtoupper((string)($in['vat_mode']??'NONE'));if(!in_array($mode,['NONE','VAT_EXCLUSIVE','VAT_INCLUSIVE'],true))accounts_fail('INVALID_VAT_MODE');$tax=$mode==='NONE'?null:billing_tax_code($db,$in['vat_tax_code_id']??0,'VAT',$date??gmdate('Y-m-d'));
 $lines=billing_invoice_lines($db,$in,(int)$client['id'],$mode,$tax);$tot=billing_totals($lines);$term=strtoupper((string)($in['payment_term']??'ADVANCE_PAYMENT'));if(!in_array($term,['ADVANCE_PAYMENT','DUE_ON_ISSUE','NET_DAYS','FIXED_DUE_DATE','CUSTOM'],true))accounts_fail('INVALID_PAYMENT_TERM');$due=isset($in['due_date'])&&$in['due_date']!==''?accounts_date($in['due_date']):null;if($term==='ADVANCE_PAYMENT'&&$due===null){}elseif($term!=='ADVANCE_PAYMENT'&&$due===null)accounts_fail('DUE_DATE_REQUIRED');
 if($id>0){$q=$db->prepare("SELECT * FROM qbook_invoices WHERE id=? FOR UPDATE");$q->execute([$id]);$old=$q->fetch();if(!$old)accounts_fail('INVOICE_NOT_FOUND',404);if($old['status']!=='DRAFT')accounts_fail('ISSUED_INVOICE_IMMUTABLE',409);if($old['origin_estimate_id']!==null)accounts_fail('ESTIMATE_CONVERTED_LINES_IMMUTABLE',409);$db->prepare("DELETE pa FROM qbook_invoice_production_allocations pa JOIN qbook_invoice_lines l ON l.id=pa.invoice_line_id WHERE l.invoice_id=? AND pa.status='DRAFT'")->execute([$id]);$db->prepare("DELETE FROM qbook_invoice_lines WHERE invoice_id=?")->execute([$id]);$ref=(int)$old['reference_no'];}
 else{$ref=billing_allocate_reference($db,'qbook_invoice_references');$db->prepare("INSERT INTO qbook_invoices(reference_no,client_id,client_name_snapshot,created_by)VALUES(?,?,?,?)")->execute([$ref,$client['id'],$client['name'],$user['id']]);$id=(int)$db->lastInsertId();}
 $db->prepare("UPDATE qbook_invoices SET client_id=?,client_name_snapshot=?,invoice_date=?,payment_term=?,terms_snapshot=?,due_date=?,vat_mode=?,vat_tax_code_id=?,vat_rate_snapshot=?,net_amount=?,vat_amount=?,total_amount=?,notes=? WHERE id=?")->execute([$client['id'],$client['name'],$date,$term,production_clean_text($in['terms']??'Advance Payment',500,'INVALID_TERMS',false),$due,$mode,$tax['id']??null,$tax['rate_percent']??null,accounts_minor_decimal($tot['net']),accounts_minor_decimal($tot['vat']),accounts_minor_decimal($tot['gross']),production_clean_text($in['notes']??'',2000,'INVALID_NOTES',false)?:null,$id]);
 $li=$db->prepare("INSERT INTO qbook_invoice_lines(invoice_id,line_no,source_type,description,quantity,unit_name,unit_price,entered_amount,taxable,net_amount,vat_amount,gross_amount,revenue_account_id,project_id,project_snapshot,mixer_id,mixer_snapshot)VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
 foreach($lines as$l){$li->execute([$id,$l['line_no'],$l['source_type'],$l['description'],$l['quantity'],$l['unit_name'],$l['unit_price_minor']===null?null:accounts_minor_decimal($l['unit_price_minor']),accounts_minor_decimal($l['entered_minor']),$l['taxable'],accounts_minor_decimal($l['net_minor']),accounts_minor_decimal($l['vat_minor']),accounts_minor_decimal($l['gross_minor']),$l['revenue_account_id'],$l['project_id'],$l['project_snapshot'],$l['mixer_id'],$l['mixer_snapshot']]);$lineId=(int)$db->lastInsertId();if($l['source_type']==='PRODUCTION_REPORT'){$p=$l['production'];if(!is_array($p))accounts_fail('PRODUCTION_ALLOCATION_REQUIRED');$sid=(int)($p['production_session_id']??0);$s=$db->prepare("SELECT ps.id,ps.status,pr.report_no,sg.total_m3 FROM qbook_production_sessions ps JOIN qbook_production_reports pr ON pr.production_session_id=ps.id JOIN qbook_production_signoffs sg ON sg.production_session_id=ps.id WHERE ps.id=? AND ps.client_id=?");$s->execute([$sid,$client['id']]);$r=$s->fetch();if(!$r||$r['status']!=='SIGNED')accounts_fail('SIGNED_PRODUCTION_REPORT_REQUIRED',409);$bm=accounts_money_minor($p['billed_m3']??'');$rate=accounts_money_minor($p['rate']??'');$billed=accounts_minor_decimal($bm);$signed=(string)$r['total_m3'];if((float)$billed>(float)$signed)accounts_fail('PRODUCTION_M3_EXCEEDED',409);$db->prepare("INSERT INTO qbook_invoice_production_allocations(invoice_line_id,production_session_id,production_report_no,report_reference_snapshot,signed_m3_snapshot,billed_m3,rate_snapshot)VALUES(?,?,?,?,?,?,?)")->execute([$lineId,$sid,$r['report_no'],production_report_reference((int)$r['report_no']),$signed,$billed,accounts_minor_decimal($rate)]);}}
 accounts_audit($db,$user,'INVOICE_DRAFT_SAVED','INVOICE',$id,['reference'=>billing_ref('INVOICE',$ref)]);return['invoice'=>['id'=>$id,'reference'=>billing_ref('INVOICE',$ref),'status'=>'DRAFT','total'=>accounts_minor_decimal($tot['gross'])]];
});});
