<?php
declare(strict_types=1);
require_once __DIR__ . '/accounts_common.php';
$user=qbook_require_user(); production_require_method('GET');
accounts_endpoint(function() use($user): array {
    $db=production_db();$admin=strtoupper((string)$user['role'])==='ADMIN';$target=(int)($_GET['custodian_user_id']??0);
    if(!$admin){if($target>0&&$target!==(int)$user['id']) accounts_fail('FORBIDDEN',403);$target=(int)$user['id'];}
    $where=$target>0?'WHERE e.custodian_user_id=?':'';$params=$target>0?[$target]:[];
    $s=$db->prepare("SELECT e.id,r.reference_no,e.line_model_version,e.custodian_user_id,u.full_name AS custodian_name,e.expense_date,e.amount,COALESCE(rc.new_expense_account_id,e.expense_account_id) AS expense_account_id,a.code AS account_code,a.name AS category,e.supplier_id,COALESCE(rc.new_supplier_paid_to,e.supplier_paid_to) AS supplier_paid_to,COALESCE(rc.new_description,e.description) AS description,COALESCE(rc.new_client_id,e.client_id) AS client_id,c.name AS client_name,COALESCE(rc.new_project_id,e.project_id) AS project_id,p.name AS project_name,COALESCE(rc.new_mixer_id,e.mixer_id) AS mixer_id,m.code AS mixer_code,e.status,e.no_receipt_reason,e.journal_id,j.reference_no AS original_journal_reference,e.reversal_journal_id,rj.reference_no AS reversal_journal_reference,rc.journal_id AS reclassification_journal_id,rcj.reference_no AS reclassification_journal_reference,rc.reason AS reclassification_reason,rc.reclassified_at,rcu.full_name AS reclassified_by_name,e.submitted_at,e.reviewed_at,e.review_reason,e.voided_by,vu.full_name AS voided_by_name,e.voided_at,e.void_reason,e.created_at,(SELECT COUNT(*) FROM qbook_financial_evidence v WHERE v.source_type='PETTY_CASH_EXPENSE' AND v.source_record_id=e.id) AS evidence_count,(SELECT MIN(v.id) FROM qbook_financial_evidence v WHERE v.source_type='PETTY_CASH_EXPENSE' AND v.source_record_id=e.id) AS evidence_id FROM qbook_petty_cash_expenses e JOIN qbook_users u ON u.id=e.custodian_user_id LEFT JOIN qbook_petty_cash_expense_reclassifications rc ON rc.id=(SELECT MAX(rc2.id) FROM qbook_petty_cash_expense_reclassifications rc2 WHERE rc2.expense_id=e.id) LEFT JOIN qbook_accounts_chart a ON a.id=COALESCE(rc.new_expense_account_id,e.expense_account_id) LEFT JOIN qbook_petty_cash_expense_references r ON r.expense_id=e.id LEFT JOIN qbook_clients c ON c.id=COALESCE(rc.new_client_id,e.client_id) LEFT JOIN qbook_projects p ON p.id=COALESCE(rc.new_project_id,e.project_id) LEFT JOIN qbook_mixers m ON m.id=COALESCE(rc.new_mixer_id,e.mixer_id) LEFT JOIN qbook_financial_journals j ON j.id=e.journal_id LEFT JOIN qbook_financial_journals rj ON rj.id=e.reversal_journal_id LEFT JOIN qbook_financial_journals rcj ON rcj.id=rc.journal_id LEFT JOIN qbook_users rcu ON rcu.id=rc.reclassified_by LEFT JOIN qbook_users vu ON vu.id=e.voided_by $where ORDER BY COALESCE(e.expense_date,DATE(e.created_at)) DESC,e.id DESC LIMIT 500");$s->execute($params);
    $rows=$s->fetchAll();$line=$db->prepare("SELECT l.*,a.code AS account_code,a.name AS category,c.name AS client_name,p.name AS project_name,m.code AS mixer_code FROM qbook_petty_cash_expense_lines l JOIN qbook_accounts_chart a ON a.id=l.expense_account_id LEFT JOIN qbook_clients c ON c.id=l.client_id LEFT JOIN qbook_projects p ON p.id=l.project_id LEFT JOIN qbook_mixers m ON m.id=l.mixer_id WHERE l.expense_id=? ORDER BY l.line_no");foreach($rows as &$row){$row['reference_no']=accounts_petty_cash_reference($row['reference_no']);$line->execute([(int)$row['id']]);$row['lines']=$line->fetchAll();if((int)$row['line_model_version']===0&&$row['lines']===[]){$row['lines']=[['id'=>null,'line_no'=>1,'item_description'=>$row['description'],'expense_account_id'=>$row['expense_account_id'],'amount'=>$row['amount'],'quantity'=>null,'unit_price'=>null,'client_id'=>$row['client_id'],'project_id'=>$row['project_id'],'mixer_id'=>$row['mixer_id'],'account_code'=>$row['account_code'],'category'=>$row['category'],'client_name'=>$row['client_name'],'project_name'=>$row['project_name'],'mixer_code'=>$row['mixer_code'],'legacy_compatibility'=>true]];}}unset($row);
    return ['expenses'=>$rows];
});
